# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 lituus-lab
"""uniimage — Python binding over the UniImage C library (EXIF + image surface)."""
from ._core import (
    version,
    abi_version,
    init,
    read_buffer,
    strip_buffer,
    edit_buffer,
    strerror,
    Image,
    Color,
    Palette,
    image_from_pixels,
    decode_buffer,
    thumbnail,
    image_abi_version,
    FMT_AUTO,
    FMT_PNG,
    FMT_JPEG,
    FMT_BMP,
    FMT_QOI,
    FMT_PNM,
    FMT_GIF,
    FMT_PCX,
    FMT_TGA,
    FMT_WEBP,
    FMT_TIFF,
    FILTER_NEAREST,
    FILTER_BILINEAR,
    FILTER_BOX,
    ROT_90,
    ROT_180,
    ROT_270,
    FLIP_H,
    FLIP_V,
    CS_GRAY,
    CS_RGB,
    CS_RGBA,
    CS_CMYK,
    CS_YUV,
    CS_INDEXED,
    COLOR_SPACE_DEFAULT,
    COLOR_SPACE_SRGB,
    COLOR_SPACE_OKLAB,
)

init()

__version__ = version()


__all__ = [
    "__version__",
    "abi_version",
    "edit_buffer",
    "read_buffer",
    "strerror",
    "strip_buffer",
    "version",
    "Image",
    "Color",
    "Palette",
    "image_from_pixels",
    "decode_buffer",
    "thumbnail",
    "image_abi_version",
    "FMT_AUTO",
    "FMT_PNG",
    "FMT_JPEG",
    "FMT_BMP",
    "FMT_QOI",
    "FMT_PNM",
    "FMT_GIF",
    "FMT_PCX",
    "FMT_TGA",
    "FMT_WEBP",
    "FMT_TIFF",
    "FILTER_NEAREST",
    "FILTER_BILINEAR",
    "FILTER_BOX",
    "ROT_90",
    "ROT_180",
    "ROT_270",
    "FLIP_H",
    "FLIP_V",
    "CS_GRAY",
    "CS_RGB",
    "CS_RGBA",
    "CS_CMYK",
    "CS_YUV",
    "CS_INDEXED",
    "COLOR_SPACE_DEFAULT",
    "COLOR_SPACE_SRGB",
    "COLOR_SPACE_OKLAB",
]
